class Article {
  final String text;
  final String domain;
  final String by;
  final String age;
  final int score;
  final int commentsCount;

  const Article({
    this.text,
    this.domain,
    this.by,
    this.age,
    this.score,
    this.commentsCount
  });
}

final articles = [
  new Article(
    text: "Cylindrical shock acoustic wasves in ionosphere triggered by launch of Formosat-5",
    domain: "wiley.com",
    by: "zdw",
    age: "3 hours",
    score: 81,
    commentsCount: 128,
  ),
  new Article(
    text: "Bmw says electric car mass production not viable till 2020",
    domain: "reuters.com",
    by: "Mononokay",
    age: "2 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Evolution is the new deep learning ",
    domain: "sentient.ai",
    by: "jonbaer",
    age: "4 hours",
    score: 200,
    commentsCount: 54,
  ),
  new Article(
    text: "Circular shock acoustic wasves in ionosphere triggered by launch of Formosat-5",
    domain: "wiley.com",
    by: "zdw",
    age: "3 hours",
    score: 81,
    commentsCount: 128,
  ),
  new Article(
    text: "Bmw says electric car mass production not viable till 2020",
    domain: "reuters.com",
    by: "Mononokay",
    age: "2 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Evolution is the new deep learning ",
    domain: "sentient.ai",
    by: "jonbaer",
    age: "4 hours",
    score: 200,
    commentsCount: 54,
  ),
  new Article(
    text: "Circular shock acoustic wasves in ionosphere triggered by launch of Formosat-5",
    domain: "wiley.com",
    by: "zdw",
    age: "3 hours",
    score: 81,
    commentsCount: 128,
  ),
  new Article(
    text: "Bmw says electric car mass production not viable till 2020",
    domain: "reuters.com",
    by: "Mononokay",
    age: "2 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Evolution is the new deep learning ",
    domain: "sentient.ai",
    by: "jonbaer",
    age: "4 hours",
    score: 200,
    commentsCount: 54,
  ),
  new Article(
    text: "Circular shock acoustic wasves in ionosphere triggered by launch of Formosat-5",
    domain: "wiley.com",
    by: "zdw",
    age: "3 hours",
    score: 81,
    commentsCount: 128,
  ),
  new Article(
    text: "Bmw says electric car mass production not viable till 2020",
    domain: "reuters.com",
    by: "Mononokay",
    age: "2 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Evolution is the new deep learning ",
    domain: "sentient.ai",
    by: "jonbaer",
    age: "4 hours",
    score: 200,
    commentsCount: 54,
  ),
  new Article(
    text: "Cylindrical shock acoustic wasves in ionosphere triggered by launch of Formosat-5",
    domain: "wiley.com",
    by: "zdw",
    age: "3 hours",
    score: 81,
    commentsCount: 128,
  ),
  new Article(
    text: "Bmw says electric car mass production not viable till 2020",
    domain: "reuters.com",
    by: "Mononokay",
    age: "2 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Evolution is the new deep learning ",
    domain: "sentient.ai",
    by: "jonbaer",
    age: "4 hours",
    score: 200,
    commentsCount: 54,
  ),
  new Article(
    text: "Circular shock acoustic wasves in ionosphere triggered by launch of Formosat-5",
    domain: "wiley.com",
    by: "zdw",
    age: "3 hours",
    score: 81,
    commentsCount: 128,
  ),
  new Article(
    text: "Bmw says electric car mass production not viable till 2020",
    domain: "reuters.com",
    by: "Mononokay",
    age: "2 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Evolution is the new deep learning ",
    domain: "sentient.ai",
    by: "jonbaer",
    age: "4 hours",
    score: 200,
    commentsCount: 54,
  ),
  new Article(
    text: "Circular shock acoustic wasves in ionosphere triggered by launch of Formosat-5",
    domain: "wiley.com",
    by: "zdw",
    age: "3 hours",
    score: 81,
    commentsCount: 128,
  ),
  new Article(
    text: "Bmw says electric car mass production not viable till 2020",
    domain: "reuters.com",
    by: "Mononokay",
    age: "2 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Evolution is the new deep learning ",
    domain: "sentient.ai",
    by: "jonbaer",
    age: "4 hours",
    score: 200,
    commentsCount: 54,
  ),
  new Article(
    text: "Circular shock acoustic wasves in ionosphere triggered by launch of Formosat-5",
    domain: "wiley.com",
    by: "zdw",
    age: "3 hours",
    score: 81,
    commentsCount: 128,
  ),
  new Article(
    text: "Bmw says electric car mass production not viable till 2020",
    domain: "reuters.com",
    by: "Mononokay",
    age: "2 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Evolution is the new deep learning ",
    domain: "sentient.ai",
    by: "jonbaer",
    age: "4 hours",
    score: 200,
    commentsCount: 54,
  ),
  new Article(
    text: "Cylindrical shock acoustic wasves in ionosphere triggered by launch of Formosat-5",
    domain: "wiley.com",
    by: "zdw",
    age: "3 hours",
    score: 81,
    commentsCount: 128,
  ),
  new Article(
    text: "Bmw says electric car mass production not viable till 2020",
    domain: "reuters.com",
    by: "Mononokay",
    age: "2 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Evolution is the new deep learning ",
    domain: "sentient.ai",
    by: "jonbaer",
    age: "4 hours",
    score: 200,
    commentsCount: 54,
  ),
  new Article(
    text: "Circular shock acoustic wasves in ionosphere triggered by launch of Formosat-5",
    domain: "wiley.com",
    by: "zdw",
    age: "3 hours",
    score: 81,
    commentsCount: 128,
  ),
  new Article(
    text: "Bmw says electric car mass production not viable till 2020",
    domain: "reuters.com",
    by: "Mononokay",
    age: "2 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Evolution is the new deep learning ",
    domain: "sentient.ai",
    by: "jonbaer",
    age: "4 hours",
    score: 200,
    commentsCount: 54,
  ),
  new Article(
    text: "Circular shock acoustic wasves in ionosphere triggered by launch of Formosat-5",
    domain: "wiley.com",
    by: "zdw",
    age: "3 hours",
    score: 81,
    commentsCount: 128,
  ),
  new Article(
    text: "Bmw says electric car mass production not viable till 2020",
    domain: "reuters.com",
    by: "Mononokay",
    age: "2 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Evolution is the new deep learning ",
    domain: "sentient.ai",
    by: "jonbaer",
    age: "4 hours",
    score: 200,
    commentsCount: 54,
  ),
  new Article(
    text: "Circular shock acoustic wasves in ionosphere triggered by launch of Formosat-5",
    domain: "wiley.com",
    by: "zdw",
    age: "3 hours",
    score: 81,
    commentsCount: 128,
  ),
  new Article(
    text: "Bmw says electric car mass production not viable till 2020",
    domain: "reuters.com",
    by: "Mononokay",
    age: "2 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Evolution is the new deep learning ",
    domain: "sentient.ai",
    by: "jonbaer",
    age: "4 hours",
    score: 200,
    commentsCount: 54,
  ),
  new Article(
    text: "Cylindrical shock acoustic wasves in ionosphere triggered by launch of Formosat-5",
    domain: "wiley.com",
    by: "zdw",
    age: "3 hours",
    score: 81,
    commentsCount: 128,
  ),
  new Article(
    text: "Bmw says electric car mass production not viable till 2020",
    domain: "reuters.com",
    by: "Mononokay",
    age: "2 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Evolution is the new deep learning ",
    domain: "sentient.ai",
    by: "jonbaer",
    age: "4 hours",
    score: 200,
    commentsCount: 54,
  ),
  new Article(
    text: "Circular shock acoustic wasves in ionosphere triggered by launch of Formosat-5",
    domain: "wiley.com",
    by: "zdw",
    age: "3 hours",
    score: 81,
    commentsCount: 128,
  ),
  new Article(
    text: "Bmw says electric car mass production not viable till 2020",
    domain: "reuters.com",
    by: "Mononokay",
    age: "2 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Evolution is the new deep learning ",
    domain: "sentient.ai",
    by: "jonbaer",
    age: "4 hours",
    score: 200,
    commentsCount: 54,
  ),
  new Article(
    text: "Circular shock acoustic wasves in ionosphere triggered by launch of Formosat-5",
    domain: "wiley.com",
    by: "zdw",
    age: "3 hours",
    score: 81,
    commentsCount: 128,
  ),
  new Article(
    text: "Bmw says electric car mass production not viable till 2020",
    domain: "reuters.com",
    by: "Mononokay",
    age: "2 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Evolution is the new deep learning ",
    domain: "sentient.ai",
    by: "jonbaer",
    age: "4 hours",
    score: 200,
    commentsCount: 54,
  ),
  new Article(
    text: "Circular shock acoustic wasves in ionosphere triggered by launch of Formosat-5",
    domain: "wiley.com",
    by: "zdw",
    age: "3 hours",
    score: 81,
    commentsCount: 128,
  ),
  new Article(
    text: "Bmw says electric car mass production not viable till 2020",
    domain: "reuters.com",
    by: "Mononokay",
    age: "2 hours",
    score: 177,
    commentsCount: 62,
  ),
  new Article(
    text: "Evolution is the new deep learning ",
    domain: "sentient.ai",
    by: "jonbaer",
    age: "4 hours",
    score: 200,
    commentsCount: 54,
  ),
];